# Basic Python

### 1. Split this string

In [ ]:
s = "Hi there Sanjay!"

In [ ]:
s.split()

['Hi', 'there', 'Sanjay!']

*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
'The diameter of {0} is {1} kilometer'.format(planet,diameter)

'The diameter of Earth is 12742 kilometer'

## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
print(d["k1"][3]["tricky"][3]["target"][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
array1=np.zeros(10)
print(array1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# array of 10 fives
array2=np.ones(10)*5
print(array2)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [ ]:
array3=np.arange(20,36,2)
print(array3)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
#Concatenate 
np.concatenate((a,b),axis=None)

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


1.numpy arrays

In [ ]:
A = np.random.randint(10, size=(3,2))
#dataframe
df = pd.DataFrame(A,columns=['cola', 'colb'])
df

cola  colb
0     8     8
1     6     2
2     8     5

2.Dictionary

In [ ]:
dict_a = {
   'col_a':[1,2,3], 
   'col_b': [2,5,6], 
}
#dataframe
df = pd.DataFrame(dict_a)
df

col_a  col_b
0      1      2
1      2      5
2      3      6

In [ ]:
3. list

In [ ]:
lst_a = [['John', 23], ['Jane', 25], ['Mary', 21]]
#dataframe
df = pd.DataFrame(lst_a,columns=['Name', 'Age'])
df

Name  Age
0  John   23
1  Jane   25
2  Mary   21

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Jan, 2023

In [5]:
import pandas as pd
  
# calling DataFrame constructor
df = pd.DataFrame()
  
# Create 6 dates
df['time'] = pd.date_range(start="1/1/2023",end="1/10/2023", freq ='24H')
  # print dataframe
  
# Extract features - year, month, day, hour, and minute
df['year'] = df['time'].dt.year
df['month'] = df['time'].dt.month
df['day'] = df['time'].dt.day

  
# Show six rows
df.head(len(df["time"]))

time  year  month  day
0 2023-01-01  2023      1    1
1 2023-01-02  2023      1    2
2 2023-01-03  2023      1    3
3 2023-01-04  2023      1    4
4 2023-01-05  2023      1    5
5 2023-01-06  2023      1    6
6 2023-01-07  2023      1    7
7 2023-01-08  2023      1    8
8 2023-01-09  2023      1    9
9 2023-01-10  2023      1   10

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
#2D list to DataFrame
df = pd.DataFrame(lists, columns =['col1',"col2","col3"]) 
df

col1 col2  col3
0     1  aaa    22
1     2  bbb    25
2     3  ccc    24